version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017-27019:27017-27019"
  post:
    build: ./post
    ports:
      - "8081:8081"
    depends_on:
      - "mongo"
  auth:
    build: ./auth
    ports:
      - "8082:8082"
  app:
    build: ./app
    ports:
      - "8080:80"
